In [2]:
from sklearn.datasets import load_files
import os

In [19]:
train_reviews = load_files(os.path.join('data/aclImdb/', 'train'), categories=["pos", "neg"])

In [18]:
test_reviews = load_files(os.path.join('data/aclImdb/', 'test'),categories=["pos", "neg"])

In [20]:
train_reviews.data[0]

b"Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.<br /><br />It is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. In terms of explaining the motives and actions of the two young suicide/murderers it is better than 'Elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see. <br /><br />Flawed but honest with a terrible honesty."

In [21]:
train_reviews.target[0]

1

In [22]:
train_reviews.data[1]

b'Words can\'t describe how bad this movie is. I can\'t explain it by writing only. You have too see it for yourself to get at grip of how horrible a movie really can be. Not that I recommend you to do that. There are so many clich\xc3\xa9s, mistakes (and all other negative things you can imagine) here that will just make you cry. To start with the technical first, there are a LOT of mistakes regarding the airplane. I won\'t list them here, but just mention the coloring of the plane. They didn\'t even manage to show an airliner in the colors of a fictional airline, but instead used a 747 painted in the original Boeing livery. Very bad. The plot is stupid and has been done many times before, only much, much better. There are so many ridiculous moments here that i lost count of it really early. Also, I was on the bad guys\' side all the time in the movie, because the good guys were so stupid. "Executive Decision" should without a doubt be you\'re choice over this one, even the "Turbulenc

In [23]:
train_reviews.target[1]

0

In [30]:
from scipy.sparse import csr_matrix
import numpy as np
import pandas as pd

In [28]:
a = np.zeros([5,5])
a[0, 3] = 1
a[4, 4] = 6
a[2, 2] = 5
a[3, 1] = 4
a[3, 2] = 2
a[1, 1] = 7

In [32]:
pd.DataFrame(a, columns=['apple','wax','sadness','luck','girl'])

apple  wax  sadness  luck  girl
0    0.0  0.0      0.0   1.0   0.0
1    0.0  7.0      0.0   0.0   0.0
2    0.0  0.0      5.0   0.0   0.0
3    0.0  4.0      2.0   0.0   0.0
4    0.0  0.0      0.0   0.0   6.0

In [33]:
b = csr_matrix(a)

In [35]:
b.todense()

matrix([[0., 0., 0., 1., 0.],
        [0., 7., 0., 0., 0.],
        [0., 0., 5., 0., 0.],
        [0., 4., 2., 0., 0.],
        [0., 0., 0., 0., 6.]])

In [36]:
b.nonzero() # в первом - строчки, где ненулевые а во втором столбцы, где у нас ненулевые значения

(array([0, 1, 2, 3, 3, 4], dtype=int32),
 array([3, 1, 2, 1, 2, 4], dtype=int32))

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

In [59]:
cv = CountVectorizer(ngram_range=(1,2))
X_train_sparce = cv.fit_transform(train_reviews.data)

In [60]:
X_test_sparce = cv.transform(test_reviews.data)

In [61]:
X_train_sparce.shape, X_test_sparce.shape

((25000, 1513832), (25000, 1513832))

In [62]:
X_train_sparce

<25000x1513832 sparse matrix of type '<class 'numpy.int64'>'
	with 8765469 stored elements in Compressed Sparse Row format>

In [63]:
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.metrics import accuracy_score

In [64]:
y_train, y_test = train_reviews.target, test_reviews.target

In [65]:
np.bincount(y_train), np.bincount(y_test)

(array([12500, 12500], dtype=int64), array([12500, 12500], dtype=int64))

In [66]:
logit = LogisticRegression(random_state=17, n_jobs=-1, solver='lbfgs')
sgd_logit = SGDClassifier(max_iter=40, random_state=17, n_jobs=-1)

In [67]:
%%time 
logit.fit(X_train_sparce, y_train)

Wall time: 53.5 s


LogisticRegression(n_jobs=-1, random_state=17)

In [68]:
%%time 
sgd_logit.fit(X_train_sparce, y_train)

Wall time: 1.82 s


SGDClassifier(max_iter=40, n_jobs=-1, random_state=17)

In [69]:
accuracy_score(y_test, logit.predict(X_test_sparce))

0.8964

In [70]:
accuracy_score(y_test, sgd_logit.predict(X_test_sparce))

0.88852

In [71]:
hash('be very nice') % 10**6

580714